create-addon: no longer link cc to gcc-10.0 since jammy
fixes LibreELEC-11.0 Add-on builds

 > [6/6] RUN ln -s /usr/bin/gcc-10 /usr/bin/cc:
#9 13.52 ln: failed to create symbolic link '/usr/bin/cc': File exists
------
Dockerfile:30
--------------------
  28 |      && rm -rf /var/lib/apt/lists/*
  29 |     
  30 | >>> RUN ln -s /usr/bin/gcc-10 /usr/bin/cc
  31 |     USER docker
  32 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c ln -s /usr/bin/gcc-10 /usr/bin/cc" did not complete successfully: exit code: 1